### ISSUE TITLE
Register vender ID

### ISSUE THREAD

**Issue by aaronbell** [Gutenberg-Labo/Otomanopee#1]
It appears that the vendor ID that you have included in the source file (`CLP`) is not yet registered with Microsoft. [Please do so here](https://docs.microsoft.com/en-us/typography/vendors/).

**Comment by Gutenberg-Labo** [comment]
Thank you for checking my files.
I have contacted Microsoft and asked them to register my vendor ID (`CLP `).
Please check the [font vendors list](https://docs.microsoft.com/en-us/typography/vendors/#c).

**Comment by aaronbell** [comment]
Great! Thank you. If you don't hear back from them, please follow up.
