### ISSUE TITLE
Missing extremes

### ISSUE THREAD

**Issue by aaronbell** [Gutenberg-Labo/Otomanopee#2]
There are a number of glyphs that are missing extremes. It is particularly important to include these, particularly in the y-direction, as they can impact the rendering of this font when hinted. 

I suggest using a Glyphs plugin such as Red Arrows, which will show you where these issues are. 

Glyphs with problems:

- D
- P
- D.full
- D.rotat
- Eth.rotat
- P.rotat
- G_u_t_e_n_b_e_r_g_space_L_a_b_o
- uni4E03
- uni5143
- uni5148
- uni5927
- uni72AC
- uni901A
- a-hira
- asmall-hira
- e-hira
- esmall-hira
- ko-hira
- go-hira
- su-hira
- so-hira
- zo-hira
- ta-hira
- da-hira
- di-hira
- nu-hira
- ne-hira
- ba-hira
- pa-hira
- pi-hira
- hu-hira
- pu-hira
- bo-hira
- po-hira
- ma-hira
- me-hira
- yo-hira
- yosmall-hira
- ri-hira
- we-hira
- a-kata
- asmall-kata
- ga-kata
- gi-kata
- ti-kata
- di-kata
- tusmall-kata
- du-kata
- nu-kata
- nusmall-kata
- hu-kata
- husmall-kata
- bu-kata
- pu-kata
- ho-kata
- hosmall-kata
- bo-kata
- po-kata
- mi-kata
- wi-kata
- vi-kata
- a-kata.half
- asmall-kata.half
- ti-kata.half
- tu-kata.half
- tusmall-kata.half
- nu-kata.half
- hu-kata.half
- ho-kata.half
- mi-kata.half
- a-kata.half.rotat
- asmall-kata.half.rotat
- tu-kata.half.rotat
- tusmall-kata.half.rotat
- nu-kata.half.rotat
- hu-kata.half.rotat
- ho-kata.half.rotat
- mi-kata.half.rotat
- question
- questiondown
- twodotenleader
- at.full
- question.full
- question.rotat
- questiondown.rotat
- twodotleader.vert
- colon.full.vert
- twodotenleader.vert
- quotesingle
- quotesingle.rotat
- at
- section
- replacementCharacter
- at.rotat
- section.rotat
- replacementCharacter.rotat

**Comment by Gutenberg-Labo** [comment]
Thanks a lot for checking glyphs and teaching me about Red Arrows plugin.
I fixed those glyphs to add extreme points and tried some more fixing with Red Arrows.

**Comment by aaronbell** [comment]
Thanks! Looks good.
