### ISSUE TITLE
Fractional coordinates

### ISSUE THREAD

**Issue by aaronbell** [Gutenberg-Labo/Otomanopee#3]
For some reason, many glyphs have points with fractional values set. While Glyphs may allow fractional funits, it is better to use whole values. 

The Red Arrows plugin can find and show these issues. 

Glyphs with this error:

- A.full
- B.full
- C.full
- D.full
- E.full
- F.full
- G.full
- H.full
- I.full
- J.full
- K.full
- L.full
- M.full
- N.full
- O.full
- P.full
- Q.full
- R.full
- S.full
- T.full
- U.full
- V.full
- W.full
- X.full
- Y.full
- Z.full
- Ntilde.rotat
- Ocircumflex.rotat
- Otilde.rotat
- E.full.vert
- a.full
- b.full
- c.full
- d.full
- e.full
- f.full
- g.full
- h.full
- i.full
- j.full
- k.full
- l.full
- m.full
- n.full
- o.full
- p.full
- q.full
- r.full
- atilde.rotat
- ecircumflex.rotat
- ntilde.rotat
- ocircumflex.rotat
- otilde.rotat
- ucircumflex.rotat
- s.full
- t.full
- u.full
- v.full
- u.full.vert
- w.full
- x.full
- y.full
- z.full
- ordfeminine
- ordmasculine
- ordfeminine.rotat
- asmall-hira
- ismall-hira
- usmall-hira
- esmall-hira
- osmall-hira
- kasmall-hira
- kesmall-hira
- tusmall-hira
- yasmall-hira
- yusmall-hira
- yosmall-hira
- wasmall-hira
- asmall-kata
- ismall-kata
- usmall-kata
- esmall-kata
- osmall-kata
- kasmall-kata
- kusmall-kata
- kesmall-kata
- sismall-kata
- susmall-kata
- tusmall-kata
- tosmall-kata
- nusmall-kata
- hasmall-kata
- hismall-kata
- husmall-kata
- hesmall-kata
- hosmall-kata
- musmall-kata
- yasmall-kata
- yusmall-kata
- yosmall-kata
- rasmall-kata
- rismall-kata
- rusmall-kata
- resmall-kata
- rosmall-kata
- wasmall-kata
- a-kata.half
- asmall-kata.half
- i-kata.half
- ismall-kata.half
- u-kata.half
- usmall-kata.half
- e-kata.half
- esmall-kata.half
- o-kata.half
- osmall-kata.half
- ka-kata.half
- ki-kata.half
- ku-kata.half
- ke-kata.half
- ko-kata.half
- sa-kata.half
- si-kata.half
- su-kata.half
- se-kata.half
- so-kata.half
- ta-kata.half
- ti-kata.half
- tu-kata.half
- tusmall-kata.half
- te-kata.half
- to-kata.half
- na-kata.half
- ni-kata.half
- nu-kata.half
- ne-kata.half
- no-kata.half
- ha-kata.half
- hi-kata.half
- hu-kata.half
- he-kata.half
- ho-kata.half
- ma-kata.half
- mi-kata.half
- mu-kata.half
- me-kata.half
- mo-kata.half
- ya-kata.half
- yasmall-kata.half
- yu-kata.half
- yusmall-kata.half
- yo-kata.half
- yosmall-kata.half
- ra-kata.half
- ri-kata.half
- ru-kata.half
- re-kata.half
- ro-kata.half
- wa-kata.half
- wo-kata.half
- n-kata.half
- asmall-kata.half.rotat
- i-kata.half.rotat
- u-kata.half.rotat
- e-kata.half.rotat
- esmall-kata.half.rotat
- osmall-kata.half.rotat
- ke-kata.half.rotat
- ko-kata.half.rotat
- sa-kata.half.rotat
- si-kata.half.rotat
- su-kata.half.rotat
- se-kata.half.rotat
- tu-kata.half.rotat
- te-kata.half.rotat
- to-kata.half.rotat
- nu-kata.half.rotat
- ne-kata.half.rotat
- ha-kata.half.rotat
- hu-kata.half.rotat
- mu-kata.half.rotat
- me-kata.half.rotat
- mo-kata.half.rotat
- yasmall-kata.half.rotat
- yu-kata.half.rotat
- yusmall-kata.half.rotat
- ra-kata.half.rotat
- ru-kata.half.rotat
- ro-kata.half.rotat
- wo-kata.half.rotat
- n-kata.half.rotat
- zero.full
- one.full
- two.full
- three.full
- four.full
- five.full
- six.full
- seven.full
- eight.full
- nine.full
- onesuperior
- twosuperior
- threesuperior
- foursuperior
- onehalf
- onequarter
- threequarters
- onesuperior.rotat
- twosuperior.rotat
- threesuperior.rotat
- onequarter.rotat
- threequarters.rotat
- ampersand.full
- asterisk.full
- at.full
- colon.full
- comma.full
- percent.full
- period.full
- semicolon.full
- backslash.full.vert
- slash.full.vert
- cent.full
- dollar.full
- sterling.full
- yen.full
- trademark
- postalmark.circled
- trademark.rotat
- apostrophemod
- commaturnedmod
- commaturnedmod.rotat
- circumflex
- tilde
- tilde.rotat
- prolonged-kana.half
-

**Comment by Gutenberg-Labo** [comment]
Thanks for pointing them out.
When I made up all glyphs and after decomposed transformed component, I completely forgot to check the fractional units.
Now I fixed them up. please check the files.

**Comment by aaronbell** [comment]
Thanks! Looks good.
