### ISSUE TITLE
Missing Latin Extended-A characters

### ISSUE THREAD

**Issue by depofree** [Gutenberg-Labo/Otomanopee#8]
Hi,

Would you be able to add additional glyphs? The ones that are missing are the following:

- ő: U+0151, &odblac;
- Ő: U+0150, &Odblac;
- ű: U+0171, &udblac;
- Ű: U+0170, &Udblac;

Thanks

**Comment by Gutenberg-Labo** [comment]
Hi, Thank you for your request.
We added the 4 glyphs (U+0150, U+0151, U+0170, U+0171) to our font.

**Comment by depofree** [comment]
HI,

Thanks for your quick help!

Cheers,
